// Flag emoji are built from a country's two-letter ISO code by mapping each
// letter to its regional indicator symbol, so only the codes need listing.
const ISO_CODES: Record<string, string> = {
  Albania: 'AL',
  Australia: 'AU',
  Austria: 'AT',
  Bangladesh: 'BD',
  Belgium: 'BE',
  'Bosnia and Herzegovina': 'BA',
  Bulgaria: 'BG',
  Canada: 'CA',
  Croatia: 'HR',
  Cyprus: 'CY',
  'Czech Republic': 'CZ',
  Czechia: 'CZ',
  Denmark: 'DK',
  Estonia: 'EE',
  Finland: 'FI',
  France: 'FR',
  Germany: 'DE',
  Greece: 'GR',
  Hungary: 'HU',
  India: 'IN',
  Ireland: 'IE',
  Italy: 'IT',
  Japan: 'JP',
  Kuwait: 'KW',
  Latvia: 'LV',
  Lithuania: 'LT',
  Luxembourg: 'LU',
  Malaysia: 'MY',
  Malta: 'MT',
  Moldova: 'MD',
  Montenegro: 'ME',
  Nepal: 'NP',
  Netherlands: 'NL',
  'New Zealand': 'NZ',
  'North Macedonia': 'MK',
  Norway: 'NO',
  Oman: 'OM',
  Pakistan: 'PK',
  Poland: 'PL',
  Portugal: 'PT',
  Qatar: 'QA',
  Romania: 'RO',
  Russia: 'RU',
  'Saudi Arabia': 'SA',
  Serbia: 'RS',
  Singapore: 'SG',
  Slovakia: 'SK',
  Slovenia: 'SI',
  'South Korea': 'KR',
  Spain: 'ES',
  'Sri Lanka': 'LK',
  Sweden: 'SE',
  Switzerland: 'CH',
  Turkey: 'TR',
  Ukraine: 'UA',
  'United Arab Emirates': 'AE',
  UAE: 'AE',
  'United Kingdom': 'GB',
  UK: 'GB',
  'United States': 'US',
  USA: 'US',
}

export function countryFlag(country: string): string {
  const code = ISO_CODES[country?.trim()]
  if (!code) return ''
  return String.fromCodePoint(...code.split('').map((c) => 0x1f1e6 + c.charCodeAt(0) - 65))
}

export const COUNTRY_NAMES = Object.keys(ISO_CODES).sort()
