-- ============================================
-- VISA MANAGEMENT SYSTEM - SUPABASE SETUP
-- ============================================

-- 1. Create admin_users table
CREATE TABLE IF NOT EXISTS admin_users (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  username TEXT UNIQUE NOT NULL DEFAULT 'admin',
  password_hash TEXT NOT NULL,
  full_name TEXT NOT NULL DEFAULT 'Admin',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Create agencies table
CREATE TABLE IF NOT EXISTS agencies (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  country TEXT NOT NULL,
  contact_person TEXT DEFAULT '',
  phone TEXT DEFAULT '',
  email TEXT DEFAULT '',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Create clients table
CREATE TABLE IF NOT EXISTS clients (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  application_id TEXT NOT NULL,
  client_name TEXT NOT NULL,
  agency_id UUID REFERENCES agencies(id),
  country TEXT DEFAULT '',
  citizenship TEXT DEFAULT '',
  passport_number TEXT DEFAULT '',
  mobile_number TEXT DEFAULT '',
  job_position TEXT DEFAULT '',
  application_status TEXT DEFAULT 'New',
  approval_status TEXT DEFAULT 'Pending',
  advance_payment NUMERIC DEFAULT 0,
  due_payment NUMERIC DEFAULT 0,
  total_payment NUMERIC DEFAULT 0,
  balance NUMERIC DEFAULT 0,
  follow_up_date DATE,
  remarks TEXT DEFAULT '',
  created_date DATE DEFAULT CURRENT_DATE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Create job_categories table
CREATE TABLE IF NOT EXISTS job_categories (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Create visa_types table
CREATE TABLE IF NOT EXISTS visa_types (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_clients_application_id ON clients(application_id);
CREATE INDEX IF NOT EXISTS idx_clients_passport ON clients(passport_number);
CREATE INDEX IF NOT EXISTS idx_clients_agency ON clients(agency_id);
CREATE INDEX IF NOT EXISTS idx_clients_status ON clients(application_status);
CREATE INDEX IF NOT EXISTS idx_clients_name ON clients(client_name);

-- 7. Insert default admin user
-- Password is 'admin123' - CHANGE THIS AFTER FIRST LOGIN!
INSERT INTO admin_users (username, password_hash, full_name)
VALUES ('admin', '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', 'Admin')
ON CONFLICT (username) DO NOTHING;

-- ============================================
-- SAMPLE DATA (Optional - remove if not needed)
-- ============================================

-- Insert sample agencies
INSERT INTO agencies (name, country, contact_person, phone, email) VALUES
  ('OPUS VIS', 'Croatia', 'John Smith', '+385-1-1234567', 'info@opusvis.hr'),
  ('ABC RECRUITMENT', 'Serbia', 'Milan Petrovic', '+381-11-1234567', 'contact@abcrecruitment.rs'),
  ('BALKAN HIRING', 'Slovenia', 'Ana Novak', '+386-1-2345678', 'info@balkanhiring.si'),
  ('EURO JOB CENTER', 'Romania', 'George Popescu', '+40-21-1234567', 'office@eurojobcenter.ro'),
  ('FUTURE EMPLOYMENT', 'Moldova', 'Ion Ivanov', '+373-22-123456', 'info@futureemployment.md')
ON CONFLICT DO NOTHING;

-- Insert sample job categories
INSERT INTO job_categories (name) VALUES
  ('Construction'), ('Factory Worker'), ('Healthcare'), ('Hospitality'),
  ('Engineering'), ('Agriculture'), ('Driver'), ('Security')
ON CONFLICT DO NOTHING;

-- Insert sample visa types
INSERT INTO visa_types (name) VALUES
  ('Work Visa'), ('Employment Visa'), ('Business Visa'), ('Tourist Visa')
ON CONFLICT DO NOTHING;

-- ============================================
-- IMPORTANT SETUP STEPS
-- ============================================
-- 1. Go to Supabase Dashboard → SQL Editor
-- 2. Copy and run this SQL
-- 3. Then go to Authentication → Providers → Enable Email provider
-- 4. For the admin password, use the bcrypt hash generated by:
--    echo "admin123" | npx ts-node -e "console.log(require('bcryptjs').hashSync(require('fs').readFileSync(0,'utf8').trim(), 10))"
-- 5. Update the admin password hash in the admin_users table
-- ============================================
